# Site settings
title: "من و سرطان خونم"
motto: "یادداشت های یک بیمار کنجکاو"
author: Amir
email: amir.asiaeetaheri@gmail.com
baseurl: "/mycancerandi" # the subpath of your site, e.g. /blog
url: "https://aasiaeet.github.io"
disqus: "aasiaeet"
keywords: "سرطان، خاطره، پزشکی"
copyright: "Commons Attribution 4.0 International"
robot: ""
description: "خاطرات شخصی در مورد تشخیص، درمان، و زندگی همراه سرطان."

long_description: "در ماراتن سرطان تنها جسم درگیر نیست، ذهن و روح هم دائم تاثیر می گذارد و می پذیرد. اینجا جایی است که تاملات و تجربیاتم در مسیر درمان و احوالات جسمی و روحی ام را به اشتراک می گذارم باشد که سود مند افتد." 

#twitter_username: mehdisadeghii
#github_username:  mehdisadeghi
fullname: "امیر"
favicon: "assets/img/bald.jpg"



#outputting
permalink: :title.html

# Build settings
markdown: Markright
kramdown:
    coderay_line_numbers: nil
encoding: utf-8
timezone: 	America/Chicago

paginate: 5
paginate_path: "/page:num/"

#tag_page_layout: tag_page
#tag_page_dir: tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: post
      author: "امیر"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts" # previously `post` in Jekyll 2.2.
    values:
      layout: post
      author: "امیر"
  -
    scope:
      path: ""
      type: projects
    values:
      layout: project

gems:
  - jekyll-sitemap
  - jalalidate
  - coderay
  - jekyll-paginate

collections:
  projects:
    output: true
